### ISSUE TITLE
Ng Serve error

### ISSUE THREAD

**Issue by acxix92** [JohnnyDevNull/ng-three-template#5]
Receiving a 'schema validation failed' error when I do ng serve. I've installed all dependencies and updated node. any insight would be helpful. here is the error log: 
"
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/alex/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)

"

**Comment by JohnnyDevNull** [comment]
Your error comes from your custom component:

```
".builders['app-shell']" should have required property 'class'
```

I think your **app-shell** is missing a property
