### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by ValiHar** [JohnnyDevNull/ng-three-template#7]
Hi there, 

seems like there is a problem with typescript v3.8.3. Gettings following error when trying to serve the template: 

`
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:98691:20)  
    at getAndCacheDiagnostics (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\Users\v.hartig\Documents\Projekte\ng-three-template\node_modules\typescript\lib\typescript.js:98688:20)
`

Any suggestions?

**Comment by andrea5586** [comment]
Currently getting this error this morning on fresh new angular project. 
In my case:

- removing `node_modules` 
- using a `package-lock.json` from a recent working project
- reinstalling dependencies with `npm i` 

worked.

I don't believe it's an issue with this repo.

**Comment by JohnnyDevNull** [comment]
This is a dependency problem with npm, only the thing mentioned by @andrea5586 will help or a complete fresh reinstall.

1. Close all your open code editors and folders that theres no open file lock  
2. Delete the node_modules folder  
3. Delete the package-lock.json  
4. Run npm install

**Comment by JohnnyDevNull** [comment]
Well because of i had this problem at work today too and many other this come from somewhere else.

The related angular issue: https://github.com/angular/angular/issues/36993

Just downgrade angular to 9.1.4 or upgrade to 9.1.6

**Comment by JohnnyDevNull** [comment]
I've done a fresh git clone, install and serve. No error. Angular Version 9.1.6 seems to work.
